# Jekyll config file

title: MU G&G
email: geeksandgadgets@live.marshall.edu
email: marshallggclub@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: '' # the subpath of your site, e.g. /blog
url: "http://mugeeks.github.io"
twitter_username: mugeeks
github_username: MUGeeksandGadgets
favicon_id: 69BBq2zn8Q

permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/

collections_dir: _collections
collections:
  - officers
  - software
  - programming
